{% set name = "node-gyp" %}
{% set version = "8.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: e9b1f24e4df7c6f6742cdc31f1ffa5e826c9d17af29915ea691311b6872e5490

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - node-gyp --help

about:
  home: https://github.com/nodejs/node-gyp
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool

extra:
  recipe-maintainers:
    - xhochy
