{% set name = "node-gyp" %}
{% set version = "8.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: c3f0c2d671dbb4154a53093d99e6ef194499e91b5d2eb9b410b20233cc894c4e

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - node-gyp --help

about:
  home: https://github.com/nodejs/node-gyp
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool

extra:
  recipe-maintainers:
    - xhochy
