{% set name = "node-gyp" %}
{% set version = "9.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 27f54782774013ab81cfd899b707aa8cbde6583a15703b2bd6dfc6bf2a070393

build:
  number: 1
  skip: true  # [win]

requirements:
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - node-gyp --help

about:
  home: https://github.com/nodejs/node-gyp
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool

extra:
  recipe-maintainers:
    - xhochy
