{% set name = "node-gyp" %}
{% set version = "8.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: f0a57644bd3ae1db9633f11de87699a402becd179c36ff3ae270d45abbf6136d

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - node-gyp --help

about:
  home: https://github.com/nodejs/node-gyp
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool

extra:
  recipe-maintainers:
    - xhochy
