{% set name = "node-gyp" %}
{% set version = "8.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 3c016adb4f0577db08d33f424eab27f376df6d3e59c2b0821ded73ba6e12e041

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - node-gyp --help

about:
  home: https://github.com/nodejs/node-gyp
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool

extra:
  recipe-maintainers:
    - xhochy
