schema_version: 1

context:
  name: node-gyp
  version: "12.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/${{ name }}/-/${{ name }}-${{ version }}.tgz
  sha256: bbe606e43a53869933de6129c5158e9b67e43952bc769986bcd877070e85fd1c

build:
  number: 0
  skip: win

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - node-gyp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool
  homepage: https://github.com/nodejs/node-gyp

extra:
  recipe-maintainers:
    - xhochy
