schema_version: 1

context:
  name: node-gyp
  version: "13.0.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/${{ name }}/-/${{ name }}-${{ version }}.tgz
  sha256: 1b1524d914331bd01312729e31a828192d53af84e113dacb6e36afabb6c21a6d

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - node-gyp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool
  homepage: https://github.com/nodejs/node-gyp

extra:
  recipe-maintainers:
    - xhochy
