schema_version: 1

context:
  name: node-gyp
  version: "13.1.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/${{ name }}/-/${{ name }}-${{ version }}.tgz
  sha256: 15663ca4944844139023390f057e86f1897d855959ea7e96f151d4873be8c71f

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - node-gyp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool
  homepage: https://github.com/nodejs/node-gyp

extra:
  recipe-maintainers:
    - xhochy
